### ISSUE TITLE
Please use 0.0.0.0 instead of 127.0.0.1

### ISSUE THREAD

**Issue by enihcam** [vokins/yhosts#59]
0.0.0.0 performs faster in DNS/IP stack, since it returns immediately without any routing logics.
You can consider that, if your DNS co-exists with Squid proxy and you also use 127.0.0.1, all blocked requests will actually be redirected to the squid server itself therefore has higher network cost.

**Comment by vokins** [comment]
Hello, glad to receive your feedback. Although 0.0.0.0 speed is very fast, but better 127.0.0.1 compatibility, android devices do not need to set up, ios devices can also be used directly. In some old android devices, 0.0.0.0 does not take effect. So in order to consider the compatibility with 127.0.0.1. Of course you can also write your own scripts, using sed alternative content, such as:
`sed 's/127.0.0.1/0.0.0.0/g'`

Thank you for feedback.

**Comment by enihcam** [comment]
Thanks for advice! That works for me.
